# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# 使用 Python 3.12 作为基础镜像
FROM python:3.12-slim

# 安装必要的依赖
RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制项目文件
COPY . /app/

# 安装 uv
RUN pip install uv

# 创建虚拟环境并安装项目
RUN uv venv
RUN uv pip install -e .

# 设置环境变量
ENV PYTHONUNBUFFERED=1

# 启动命令
CMD ["uvx", "weixin_search_mcp", "--transport", "stdio"]
